use "net"
use "runner"
use "tests"

actor Main
  new create(env: Env) =>
    let args = env.args
    if args.size() < 3 then
      env.err.print("usage: http11test <host> <service>")
      env.exitcode(2)
      return
    end

    let host = try args(1)? else "" end
    let service = try args(2)? else "80" end

    let auth = TCPConnectAuth(env.root)

    let cases: Array[RejectSpec val] val = recover val
      [ as RejectSpec val:
        UriTooLong(host)
        UnknownMethod(host)
        MissingHost(host)
        DuplicateHost(host)
        HeaderWhitespace(host)
        GarbageBytes(host)
        BareCr(host)
        ObsFold(host)
        OversizeHeader(host)
        InvalidContentLength(host)
        LeadingCrlf(host)
        NoRequestLineJustCrlf(host)
        TabBeforeColon(host)
        MethodWithSpace(host)
        TabBetweenMethodAndTarget(host)
      ]
    end

    // Count: RejectSpec list + any custom-shape tests instantiated below.
    let reporter = Reporter(env, cases.size() + 239)

    for spec in cases.values() do
      RejectRunner(auth, host, service, spec, reporter)
    end

    HeadParityRunner(auth, host, service, reporter)
    PersistentConnectionRunner(auth, host, service, reporter)
    ConnectionCloseRunner(auth, host, service, reporter)
    ContentLengthAccuracy(auth, host, service, reporter)
    DateHeaderFormat(auth, host, service, reporter)
    PipelineOrder(auth, host, service, reporter)
    ContentTypeOnBody(auth, host, service, reporter)
    NoObsFoldInResponse(auth, host, service, reporter)
    EchoesConnectionClose(auth, host, service, reporter)
    NoBareCrInResponse(auth, host, service, reporter)
    ResponseHttpVersion(auth, host, service, reporter)
    HeadClParity(auth, host, service, reporter)
    OptionsReturnsAllow(auth, host, service, reporter)
    TraceReflects(auth, host, service, reporter)
    OptionsAsterisk(auth, host, service, reporter)
    HeadHasDate(auth, host, service, reporter)
    BrowserStyleRequest(auth, host, service, reporter)
    ContentTypeWellFormed(auth, host, service, reporter)
    ThreePersistentHeads(auth, host, service, reporter)
    GetWithQueryString(auth, host, service, reporter)
    HeadGetStatusParity(auth, host, service, reporter)
    ResponseHasFraming(auth, host, service, reporter)
    NoOwsAfterColon(auth, host, service, reporter)
    MultipleConnectionOptions(auth, host, service, reporter)
    HostWithPort(auth, host, service, reporter)
    HeadGetCtParity(auth, host, service, reporter)
    MultipleConnectionLines(auth, host, service, reporter)
    HeadGetServerParity(auth, host, service, reporter)
    AcceptWildcard(auth, host, service, reporter)
    NoTeWithCl(auth, host, service, reporter)
    IfModifiedSinceOld(auth, host, service, reporter)
    AcceptEncodingIdentity(auth, host, service, reporter)
    WithCookie(auth, host, service, reporter)
    MultiAcceptEncoding(auth, host, service, reporter)
    WithAuthorization(auth, host, service, reporter)
    WithReferer(auth, host, service, reporter)
    WithXForwardedFor(auth, host, service, reporter)
    WithAcceptLanguage(auth, host, service, reporter)
    WithCacheControl(auth, host, service, reporter)
    PercentEncodedPath(auth, host, service, reporter)
    EmptyQueryString(auth, host, service, reporter)
    LongUserAgent(auth, host, service, reporter)
    DeepPath(auth, host, service, reporter)
    PlusInQuery(auth, host, service, reporter)
    HostAsIp(auth, host, service, reporter)
    EmptyHeaderValue(auth, host, service, reporter)
    WhitespaceInHeaderValue(auth, host, service, reporter)
    LongQueryString(auth, host, service, reporter)
    AbsoluteFormTarget(auth, host, service, reporter)
    ManyHeaders(auth, host, service, reporter)
    MultipleSlashesInPath(auth, host, service, reporter)
    WithOrigin(auth, host, service, reporter)
    IfNoneMatchPresent(auth, host, service, reporter)
    AcceptMultipleTypes(auth, host, service, reporter)
    UpgradeInsecureRequests(auth, host, service, reporter)
    Http10Request(auth, host, service, reporter)
    HeaderValueLeadingOws(auth, host, service, reporter)
    WithSecFetch(auth, host, service, reporter)
    WithVia(auth, host, service, reporter)
    WithClientDate(auth, host, service, reporter)
    WithAcceptCharset(auth, host, service, reporter)
    WithDnt(auth, host, service, reporter)
    RangeHeaderHandled(auth, host, service, reporter)
    ExtraWhitespaceInRequestLine(auth, host, service, reporter)
    NoDuplicateContentLength(auth, host, service, reporter)
    NoDuplicateDate(auth, host, service, reporter)
    NoDuplicateServer(auth, host, service, reporter)
    NoDuplicateConnection(auth, host, service, reporter)
    WithExpect100Continue(auth, host, service, reporter)
    WithPragmaNoCache(auth, host, service, reporter)
    MinimalRequest(auth, host, service, reporter)
    PostEmptyBody(auth, host, service, reporter)
    PathWithDotDot(auth, host, service, reporter)
    WithMaxForwards(auth, host, service, reporter)
    WithTeTrailers(auth, host, service, reporter)
    WithFromHeader(auth, host, service, reporter)
    WithWarningHeader(auth, host, service, reporter)
    WithXCustomHeader(auth, host, service, reporter)
    PathWithDotSegment(auth, host, service, reporter)
    ManyQueryParams(auth, host, service, reporter)
    RepeatedQueryKey(auth, host, service, reporter)
    GetWithBody(auth, host, service, reporter)
    EmptyHostValue(auth, host, service, reporter)
    LowercaseMethod(auth, host, service, reporter)
    PutWithBody(auth, host, service, reporter)
    ChunkedBodyPost(auth, host, service, reporter)
    TwoCookieHeaders(auth, host, service, reporter)
    DeleteMethod(auth, host, service, reporter)
    PatchWithBody(auth, host, service, reporter)
    ChunkedMultiChunk(auth, host, service, reporter)
    ChunkedUppercaseHex(auth, host, service, reporter)
    ChunkedWithExtension(auth, host, service, reporter)
    ChunkedWithTrailer(auth, host, service, reporter)
    PipelinePostThenGet(auth, host, service, reporter)
    DuplicateClSameValue(auth, host, service, reporter)
    Http10KeepAlive(auth, host, service, reporter)
    Expect100WithBody(auth, host, service, reporter)
    ResponseHasServerHeader(auth, host, service, reporter)
    GetHasDate(auth, host, service, reporter)
    TeValueSubstringMatch(auth, host, service, reporter)
    InvalidHeaderNameChar(auth, host, service, reporter)
    HeaderValueWithQuotes(auth, host, service, reporter)
    HeaderValueWithSemicolons(auth, host, service, reporter)
    PercentEncodedSlash(auth, host, service, reporter)
    PercentEncodedUnicode(auth, host, service, reporter)
    PersistentHeadThenGet(auth, host, service, reporter)
    ResponseReasonPhraseAscii(auth, host, service, reporter)
    PathWithTilde(auth, host, service, reporter)
    HeaderNameUppercase(auth, host, service, reporter)
    GetWithFragment(auth, host, service, reporter)
    PathWithSpecialChars(auth, host, service, reporter)
    ConnectionUpgradeOnly(auth, host, service, reporter)
    HeaderWithOnlyOwsValue(auth, host, service, reporter)
    HeaderValueWithParens(auth, host, service, reporter)
    HighBitInHeaderName(auth, host, service, reporter)
    NegativeContentLength(auth, host, service, reporter)
    ClWithPlusSign(auth, host, service, reporter)
    ClWithHexValue(auth, host, service, reporter)
    ConnectMethod(auth, host, service, reporter)
    DigitOnlyHeaderName(auth, host, service, reporter)
    AllTcharsHeaderName(auth, host, service, reporter)
    TeChunkedNotLast(auth, host, service, reporter)
    TeIdentityOnly(auth, host, service, reporter)
    MethodMixedCase(auth, host, service, reporter)
    ClMultipleSameLine(auth, host, service, reporter)
    ClWithTrailingSpace(auth, host, service, reporter)
    HeaderValueWithBraces(auth, host, service, reporter)
    DoubleTeChunkedHeader(auth, host, service, reporter)
    PercentNullInPath(auth, host, service, reporter)
    PercentCrlfInPath(auth, host, service, reporter)
    InvalidPercentEncoding(auth, host, service, reporter)
    HostWithBadPort(auth, host, service, reporter)
    Http12Request(auth, host, service, reporter)
    HttpLowercaseName(auth, host, service, reporter)
    DuplicateXCustomHeader(auth, host, service, reporter)
    OptionsSpecificPath(auth, host, service, reporter)
    EmptyRequestLine(auth, host, service, reporter)
    CorsPreflight(auth, host, service, reporter)
    BodyLongerThanCl(auth, host, service, reporter)
    CookieWithQuotedValue(auth, host, service, reporter)
    AcceptWithQvalues(auth, host, service, reporter)
    IdnHost(auth, host, service, reporter)
    HostWithIpv6(auth, host, service, reporter)
    IfModifiedSinceFuture(auth, host, service, reporter)
    IfModifiedSinceMalformed(auth, host, service, reporter)
    MultipleAuthorization(auth, host, service, reporter)
    Http10ChunkedRejected(auth, host, service, reporter)
    PathWithSemicolonParams(auth, host, service, reporter)
    HostWithUserinfo(auth, host, service, reporter)
    EncodedDotDotTraversal(auth, host, service, reporter)
    TruncatedPercentEncoding(auth, host, service, reporter)
    ThreeMethodPipeline(auth, host, service, reporter)
    ClWithLeadingZeros(auth, host, service, reporter)
    NulInHeaderValue(auth, host, service, reporter)
    CharsetInContentType(auth, host, service, reporter)
    HeaderValueLeadingTab(auth, host, service, reporter)
    HeaderValueWithColons(auth, host, service, reporter)
    AcceptZeroQvalue(auth, host, service, reporter)
    DuplicateHostSameValue(auth, host, service, reporter)
    BareCrInValue(auth, host, service, reporter)
    DelInValue(auth, host, service, reporter)
    ObsTextInValue(auth, host, service, reporter)
    UriWithOnlyQuery(auth, host, service, reporter)
    ManyCookiesOneHeader(auth, host, service, reporter)
    PathWithAtSign(auth, host, service, reporter)
    TraceWithBody(auth, host, service, reporter)
    EmptyAcceptEncoding(auth, host, service, reporter)
    EmptyUserAgent(auth, host, service, reporter)
    OptionsWithBody(auth, host, service, reporter)
    HugeQueryString(auth, host, service, reporter)
    HeaderFieldNameWithUnderscore(auth, host, service, reporter)
    ForwardedHeader(auth, host, service, reporter)
    ConnectionWithOws(auth, host, service, reporter)
    IfMatchWildcard(auth, host, service, reporter)
    SecWebsocketUpgrade(auth, host, service, reporter)
    ClWithTabOws(auth, host, service, reporter)
    MultipleAcceptLines(auth, host, service, reporter)
    RangeOpenEnded(auth, host, service, reporter)
    RangeSuffix(auth, host, service, reporter)
    RangeMultipleByteranges(auth, host, service, reporter)
    ConnectionDuplicateClose(auth, host, service, reporter)
    ChunkedExtensionEmpty(auth, host, service, reporter)
    UrlEndingQuestionMark(auth, host, service, reporter)
    UrlDoubleQuestionMark(auth, host, service, reporter)
    LongMethodName(auth, host, service, reporter)
    ChunkedSizeWithLowercaseHex(auth, host, service, reporter)
    UrlWithAtInAuthority(auth, host, service, reporter)
    DoubleSlashAtRoot(auth, host, service, reporter)
    PortTooLargeInHost(auth, host, service, reporter)
    HostIpv6NoBrackets(auth, host, service, reporter)
    MethodWithDigits(auth, host, service, reporter)
    GetWithHugeHeaderCount(auth, host, service, reporter)
    GetWithKbHeaderValue(auth, host, service, reporter)
    SingleCharFieldName(auth, host, service, reporter)
    FiveGetPipeline(auth, host, service, reporter)
    PostClZeroWithBodyBytes(auth, host, service, reporter)
    HeaderNameOneCharSpecial(auth, host, service, reporter)
    HostWithPortZero(auth, host, service, reporter)
    HostWithTrailingDot(auth, host, service, reporter)
    HeaderValueWithEquals(auth, host, service, reporter)
    ConnectionTeToken(auth, host, service, reporter)
    NoHostHeader(auth, host, service, reporter)
    Http2Preface(auth, host, service, reporter)
    BrotliAcceptEncoding(auth, host, service, reporter)
    OriginNull(auth, host, service, reporter)
    LinkMethod(auth, host, service, reporter)
    ProxyAuthorization(auth, host, service, reporter)
    WeakEtagIfNoneMatch(auth, host, service, reporter)
    MultipleContentType(auth, host, service, reporter)
    BareLfRequest(auth, host, service, reporter)
    TeBeforeClSmuggling(auth, host, service, reporter)
    ClBeforeTeSmuggling(auth, host, service, reporter)
    KeepAliveHeader(auth, host, service, reporter)
    PostHeadPipeline(auth, host, service, reporter)
    EmptyRequestThenClose(auth, host, service, reporter)
    AcceptStarAlone(auth, host, service, reporter)
    WebdavCopyMethod(auth, host, service, reporter)
    DeleteWithBody(auth, host, service, reporter)
    QueryStringEdges(auth, host, service, reporter)
    PathWithEncodedSpace(auth, host, service, reporter)
    DigestAuthorization(auth, host, service, reporter)
    EmptyBearerToken(auth, host, service, reporter)
    GetWithStarTarget(auth, host, service, reporter)
    HeadWithContentLength(auth, host, service, reporter)
    HostWithInternalSpace(auth, host, service, reporter)
    PathDoubleEncodedTraversal(auth, host, service, reporter)
    HostWithLeadingDot(auth, host, service, reporter)
    UnknownExpectation(auth, host, service, reporter)
    ConflictingConnectionLines(auth, host, service, reporter)
    HeadWithRequestBody(auth, host, service, reporter)
    ManyTabsAfterColon(auth, host, service, reporter)
    HeaderValueStartsWithColon(auth, host, service, reporter)
    GetHugeHostName(auth, host, service, reporter)
    PathWithCurlyBraces(auth, host, service, reporter)
    PathWithBackslash(auth, host, service, reporter)
    PathWithPipe(auth, host, service, reporter)
    PathWithCaret(auth, host, service, reporter)
    AcceptWithSubparams(auth, host, service, reporter)
    DateInRequest(auth, host, service, reporter)
