use "net"
use "runner"
use "tests"

actor Main
  new create(env: Env) =>
    let args = env.args
    if args.size() < 3 then
      env.err.print("usage: http11test <host> <service>")
      env.exitcode(2)
      return
    end

    let host = try args(1)? else "" end
    let service = try args(2)? else "80" end

    let auth = TCPConnectAuth(env.root)

    let cases: Array[RejectSpec val] val = recover val
      [ as RejectSpec val:
        UriTooLong(host)
        UnknownMethod(host)
        MissingHost(host)
        DuplicateHost(host)
        HeaderWhitespace(host)
        GarbageBytes(host)
        BareCr(host)
        ObsFold(host)
        OversizeHeader(host)
        InvalidContentLength(host)
        LeadingCrlf(host)
      ]
    end

    // Count: RejectSpec list + any custom-shape tests instantiated below.
    let reporter = Reporter(env, cases.size() + 100)

    for spec in cases.values() do
      RejectRunner(auth, host, service, spec, reporter)
    end

    HeadParityRunner(auth, host, service, reporter)
    PersistentConnectionRunner(auth, host, service, reporter)
    ConnectionCloseRunner(auth, host, service, reporter)
    ContentLengthAccuracy(auth, host, service, reporter)
    DateHeaderFormat(auth, host, service, reporter)
    PipelineOrder(auth, host, service, reporter)
    ContentTypeOnBody(auth, host, service, reporter)
    NoObsFoldInResponse(auth, host, service, reporter)
    EchoesConnectionClose(auth, host, service, reporter)
    NoBareCrInResponse(auth, host, service, reporter)
    ResponseHttpVersion(auth, host, service, reporter)
    HeadClParity(auth, host, service, reporter)
    OptionsReturnsAllow(auth, host, service, reporter)
    TraceReflects(auth, host, service, reporter)
    OptionsAsterisk(auth, host, service, reporter)
    HeadHasDate(auth, host, service, reporter)
    BrowserStyleRequest(auth, host, service, reporter)
    ContentTypeWellFormed(auth, host, service, reporter)
    ThreePersistentHeads(auth, host, service, reporter)
    GetWithQueryString(auth, host, service, reporter)
    HeadGetStatusParity(auth, host, service, reporter)
    ResponseHasFraming(auth, host, service, reporter)
    NoOwsAfterColon(auth, host, service, reporter)
    MultipleConnectionOptions(auth, host, service, reporter)
    HostWithPort(auth, host, service, reporter)
    HeadGetCtParity(auth, host, service, reporter)
    MultipleConnectionLines(auth, host, service, reporter)
    HeadGetServerParity(auth, host, service, reporter)
    AcceptWildcard(auth, host, service, reporter)
    NoTeWithCl(auth, host, service, reporter)
    IfModifiedSinceOld(auth, host, service, reporter)
    AcceptEncodingIdentity(auth, host, service, reporter)
    WithCookie(auth, host, service, reporter)
    MultiAcceptEncoding(auth, host, service, reporter)
    WithAuthorization(auth, host, service, reporter)
    WithReferer(auth, host, service, reporter)
    WithXForwardedFor(auth, host, service, reporter)
    WithAcceptLanguage(auth, host, service, reporter)
    WithCacheControl(auth, host, service, reporter)
    PercentEncodedPath(auth, host, service, reporter)
    EmptyQueryString(auth, host, service, reporter)
    LongUserAgent(auth, host, service, reporter)
    DeepPath(auth, host, service, reporter)
    PlusInQuery(auth, host, service, reporter)
    HostAsIp(auth, host, service, reporter)
    EmptyHeaderValue(auth, host, service, reporter)
    WhitespaceInHeaderValue(auth, host, service, reporter)
    LongQueryString(auth, host, service, reporter)
    AbsoluteFormTarget(auth, host, service, reporter)
    ManyHeaders(auth, host, service, reporter)
    MultipleSlashesInPath(auth, host, service, reporter)
    WithOrigin(auth, host, service, reporter)
    IfNoneMatchPresent(auth, host, service, reporter)
    AcceptMultipleTypes(auth, host, service, reporter)
    UpgradeInsecureRequests(auth, host, service, reporter)
    Http10Request(auth, host, service, reporter)
    HeaderValueLeadingOws(auth, host, service, reporter)
    WithSecFetch(auth, host, service, reporter)
    WithVia(auth, host, service, reporter)
    WithClientDate(auth, host, service, reporter)
    WithAcceptCharset(auth, host, service, reporter)
    WithDnt(auth, host, service, reporter)
    RangeHeaderHandled(auth, host, service, reporter)
    ExtraWhitespaceInRequestLine(auth, host, service, reporter)
    NoDuplicateContentLength(auth, host, service, reporter)
    NoDuplicateDate(auth, host, service, reporter)
    NoDuplicateServer(auth, host, service, reporter)
    NoDuplicateConnection(auth, host, service, reporter)
    WithExpect100Continue(auth, host, service, reporter)
    WithPragmaNoCache(auth, host, service, reporter)
    MinimalRequest(auth, host, service, reporter)
    PostEmptyBody(auth, host, service, reporter)
    PathWithDotDot(auth, host, service, reporter)
    WithMaxForwards(auth, host, service, reporter)
    WithTeTrailers(auth, host, service, reporter)
    WithFromHeader(auth, host, service, reporter)
    WithWarningHeader(auth, host, service, reporter)
    WithXCustomHeader(auth, host, service, reporter)
    PathWithDotSegment(auth, host, service, reporter)
    ManyQueryParams(auth, host, service, reporter)
    RepeatedQueryKey(auth, host, service, reporter)
    GetWithBody(auth, host, service, reporter)
    EmptyHostValue(auth, host, service, reporter)
    LowercaseMethod(auth, host, service, reporter)
    PutWithBody(auth, host, service, reporter)
    ChunkedBodyPost(auth, host, service, reporter)
    TwoCookieHeaders(auth, host, service, reporter)
    DeleteMethod(auth, host, service, reporter)
    PatchWithBody(auth, host, service, reporter)
    ChunkedMultiChunk(auth, host, service, reporter)
    ChunkedUppercaseHex(auth, host, service, reporter)
    ChunkedWithExtension(auth, host, service, reporter)
    ChunkedWithTrailer(auth, host, service, reporter)
    PipelinePostThenGet(auth, host, service, reporter)
    DuplicateClSameValue(auth, host, service, reporter)
    Http10KeepAlive(auth, host, service, reporter)
    Expect100WithBody(auth, host, service, reporter)
    ResponseHasServerHeader(auth, host, service, reporter)
    GetHasDate(auth, host, service, reporter)
    TeValueSubstringMatch(auth, host, service, reporter)
