use "net"
use "../wire"
use "../runner"

actor DateHeaderFormat is WireCallback
  """
  Covers two intersecting requirements that together fail loudly on
  browser cache logic when broken:

  - rfc9110-6.6.1-02 (MUST): an origin server with a clock generates a
    Date header in all 2xx/3xx/4xx responses.
  - rfc9110-5.6.7-02 (MUST): HTTP-date fields generated by senders MUST
    use the IMF-fixdate format ("Sun, 06 Nov 1994 08:49:37 GMT").

  We send GET / (a 2xx-serving request), look for a Date header, and
  validate its value structurally.
  """
  let _reporter: Reporter
  let _test_id: String = "rfc9110-5.6.7-02"

  new create(
    auth: TCPConnectAuth,
    host: String,
    service: String,
    reporter: Reporter)
  =>
    _reporter = reporter

    let request = recover val
      let s = String
      s.append("GET / HTTP/1.1\r\nHost: ")
      s.append(host)
      s.append("\r\nConnection: close\r\n\r\n")
      s
    end

    WireClient(auth, host, service, request, this)

  be on_response(bytes: Array[U8] val) =>
    match ResponseParser.status_code(bytes)
    | let code: U16 =>
      if (code < 200) or (code >= 500) then
        _reporter.fail(_test_id,
          "GET / returned " + code.string() + " (target should serve 2xx)")
        return
      end
    | let err: ParseError =>
      _reporter.fail(_test_id, err.describe())
      return
    end

    match ResponseParser.find_header_value(bytes, "date")
    | let value: String =>
      if ImfFixdate.is_valid(value) then
        _reporter.pass(_test_id)
      else
        _reporter.fail(_test_id,
          "Date header not in IMF-fixdate format: \"" + value + "\"")
      end
    | None =>
      _reporter.fail(_test_id,
        "no Date header in response (rfc9110-6.6.1-02)")
    end

  be on_error(reason: String) =>
    _reporter.fail(_test_id, reason)
