primitive ImfFixdate
  """
  Syntactic validator for the IMF-fixdate format required by RFC 9110
  §5.6.7 for HTTP-date fields generated by senders.

  Format: "Sun, 06 Nov 1994 08:49:37 GMT" — exactly 29 characters.
  This validates structure (day-name, month, digit positions, separators)
  but not semantic plausibility (e.g. day 31 in February is accepted).
  """
  fun is_valid(value: String): Bool =>
    if value.size() != 29 then return false end
    try
      // 0-2: day-name
      if not _is_day_name(value(0)?, value(1)?, value(2)?) then return false end
      // 3-4: ", "
      if value(3)? != ',' then return false end
      if value(4)? != ' ' then return false end
      // 5-6: 2-digit day
      if not _is_digit(value(5)?) then return false end
      if not _is_digit(value(6)?) then return false end
      // 7: " "
      if value(7)? != ' ' then return false end
      // 8-10: month
      if not _is_month(value(8)?, value(9)?, value(10)?) then return false end
      // 11: " "
      if value(11)? != ' ' then return false end
      // 12-15: 4-digit year
      var i: USize = 12
      while i < 16 do
        if not _is_digit(value(i)?) then return false end
        i = i + 1
      end
      // 16: " "
      if value(16)? != ' ' then return false end
      // 17-18: 2-digit hour
      if not _is_digit(value(17)?) then return false end
      if not _is_digit(value(18)?) then return false end
      // 19: ":"
      if value(19)? != ':' then return false end
      // 20-21: 2-digit minute
      if not _is_digit(value(20)?) then return false end
      if not _is_digit(value(21)?) then return false end
      // 22: ":"
      if value(22)? != ':' then return false end
      // 23-24: 2-digit second
      if not _is_digit(value(23)?) then return false end
      if not _is_digit(value(24)?) then return false end
      // 25: " "
      if value(25)? != ' ' then return false end
      // 26-28: "GMT"
      if value(26)? != 'G' then return false end
      if value(27)? != 'M' then return false end
      if value(28)? != 'T' then return false end
      true
    else
      false
    end

  fun _is_digit(b: U8): Bool =>
    (b >= '0') and (b <= '9')

  fun _is_day_name(a: U8, b: U8, c: U8): Bool =>
    ((a == 'S') and (b == 'u') and (c == 'n'))
      or ((a == 'M') and (b == 'o') and (c == 'n'))
      or ((a == 'T') and (b == 'u') and (c == 'e'))
      or ((a == 'W') and (b == 'e') and (c == 'd'))
      or ((a == 'T') and (b == 'h') and (c == 'u'))
      or ((a == 'F') and (b == 'r') and (c == 'i'))
      or ((a == 'S') and (b == 'a') and (c == 't'))

  fun _is_month(a: U8, b: U8, c: U8): Bool =>
    ((a == 'J') and (b == 'a') and (c == 'n'))
      or ((a == 'F') and (b == 'e') and (c == 'b'))
      or ((a == 'M') and (b == 'a') and (c == 'r'))
      or ((a == 'A') and (b == 'p') and (c == 'r'))
      or ((a == 'M') and (b == 'a') and (c == 'y'))
      or ((a == 'J') and (b == 'u') and (c == 'n'))
      or ((a == 'J') and (b == 'u') and (c == 'l'))
      or ((a == 'A') and (b == 'u') and (c == 'g'))
      or ((a == 'S') and (b == 'e') and (c == 'p'))
      or ((a == 'O') and (b == 'c') and (c == 't'))
      or ((a == 'N') and (b == 'o') and (c == 'v'))
      or ((a == 'D') and (b == 'e') and (c == 'c'))
