server.document-root = "/var/www"
server.port           = 80
server.bind           = "0.0.0.0"

index-file.names      = ( "index.html" )

mimetype.assign = (
  ".html" => "text/html",
  ".txt"  => "text/plain"
)
